# Generated by Django 2.0.3 on 2021-09-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='name',
            new_name='uid',
        ),
    ]
