# Generated by Django 2.0.3 on 2021-11-10 07:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_time_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=230)),
                ('ordering', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collection Charge',
                'verbose_name_plural': 'Collection Charge',
            },
        ),
        migrations.CreateModel(
            name='CollectionPointEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_point_name_bangla', models.CharField(max_length=230)),
                ('collection_point_name_english', models.CharField(max_length=230)),
                ('ordering', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('slugan', models.CharField(blank=True, max_length=100)),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('email1', models.EmailField(blank=True, max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100)),
                ('mobile1', models.CharField(blank=True, max_length=15)),
                ('mobile2', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('pro_details', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('favicon_logo', models.ImageField(upload_to='images/logo')),
                ('about_content', models.TextField(blank=True)),
                ('about_images', models.ImageField(upload_to='images/about_images')),
                ('why_buy', models.TextField(blank=True)),
                ('map_locationo', models.TextField(blank=True)),
                ('facebook_link', models.TextField(blank=True)),
                ('instagram_link', models.TextField(blank=True)),
                ('youtube_link', models.TextField(blank=True)),
                ('linkedin_link', models.TextField(blank=True)),
                ('staring_year', models.IntegerField()),
                ('copy_right', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'courier Profile',
                'verbose_name_plural': 'courier Profile Information',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('COD_persent', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('collection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.CollectionPointEntry')),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charge',
            },
        ),
        migrations.CreateModel(
            name='DeliveryChargeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge Location',
                'verbose_name_plural': 'Delivery Charge Location',
            },
        ),
        migrations.CreateModel(
            name='DeliveryChargeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge Weight Category',
                'verbose_name_plural': 'Delivery Charge Weight Category',
            },
        ),
        migrations.CreateModel(
            name='DistrictEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name_bangla', models.CharField(max_length=230)),
                ('district_name_english', models.CharField(max_length=230)),
                ('ordering', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hub_name_bangla', models.CharField(max_length=230)),
                ('Hub_name_english', models.CharField(max_length=230)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact_no1', models.CharField(max_length=50)),
                ('contact_no2', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marchant_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact_no1', models.CharField(max_length=50)),
                ('contact_no2', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/merchant_logo')),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('district_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact_no1', models.CharField(max_length=50)),
                ('contact_no2', models.CharField(max_length=50)),
                ('reference_no', models.CharField(max_length=50)),
                ('actual_package_price', models.IntegerField(default=0)),
                ('collection_date', models.CharField(max_length=50)),
                ('only_delivery', models.BooleanField(default=False)),
                ('delivery_and_amount_collection', models.BooleanField(default=False)),
                ('lequed_or_Fragile', models.BooleanField(default=False)),
                ('addtional_note', models.TextField()),
                ('shipment_charge', models.CharField(blank=True, max_length=50)),
                ('cod_charge', models.CharField(blank=True, max_length=50)),
                ('lequed_or_Fragile_charge', models.CharField(blank=True, max_length=50)),
                ('total_service_charge', models.CharField(blank=True, max_length=50)),
                ('collection_amount', models.CharField(blank=True, max_length=50)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('order_status', models.CharField(blank=True, choices=[('1', 'order_placed'), ('2', 'customer_absent'), ('3', 'in_sorting'), ('4', 'payment_done')], max_length=1)),
                ('collection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.CollectionPointEntry')),
                ('collection_time_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.Collection_time_category')),
                ('district_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
                ('merchant_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PackegeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packege_name', models.CharField(max_length=230)),
                ('ordering', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostOfficeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_office_bangla', models.CharField(max_length=230)),
                ('post_office_english', models.CharField(max_length=230)),
                ('post_code', models.CharField(max_length=230)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Return Charge',
                'verbose_name_plural': 'Return Charge',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_icon', models.CharField(blank=True, max_length=50)),
                ('service_details', ckeditor.fields.RichTextField(blank=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(blank=True, max_length=100)),
                ('title1', models.CharField(blank=True, max_length=200)),
                ('title2', models.CharField(blank=True, max_length=200)),
                ('slider_images', models.ImageField(upload_to='images/slider')),
                ('slider_link', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slider_order', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
            },
        ),
        migrations.CreateModel(
            name='UnionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_name_bangla', models.CharField(max_length=230)),
                ('union_name_english', models.CharField(max_length=230)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UpazillaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upazilla_name_bangla', models.CharField(max_length=230)),
                ('upazilla_name_english', models.CharField(max_length=230)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
            ],
        ),
        migrations.CreateModel(
            name='WhyBest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why we are the best',
                'verbose_name_plural': 'Why we are the best',
            },
        ),
        migrations.DeleteModel(
            name='Custom',
        ),
        migrations.AddField(
            model_name='unionentry',
            name='upazilla_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry'),
        ),
        migrations.AddField(
            model_name='postofficeinfo',
            name='upazilla_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='packegeType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.PackegeType'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='post_office_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.PostOfficeInfo'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='upazilla_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeWeight'),
        ),
        migrations.AddField(
            model_name='merchantinfo',
            name='upazilla_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry'),
        ),
        migrations.AddField(
            model_name='hubinfo',
            name='upazilla_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry'),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='delivery_charge_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeLocation'),
        ),
        migrations.AddField(
            model_name='deliverycharge',
            name='delivery_charge_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeWeight'),
        ),
    ]
