# Generated by Django 2.0.3 on 2021-11-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0002_auto_20211110_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='collection_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='contact_no1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='contact_no2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
