# Generated by Django 2.0.3 on 2021-09-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0002_auto_20210905_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
