# Generated by Django 2.0.3 on 2021-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0004_merchantorder_order_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='order_track',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('2', 'picked'), ('3', 'in_transit'), ('4', 'delivered'), ('5', 'hold'), ('6', 'return_pending'), ('7', 'return_to_hub '), ('8', 'return_to_merchent'), ('9', 'canceled')], default='1', max_length=1),
        ),
    ]
