# Generated by Django 2.0.3 on 2021-11-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0005_auto_20211123_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='canceled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='hold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='in_transit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='picked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_pending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_to_hub_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_to_merchent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
