# Generated by Django 2.0.3 on 2021-12-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0005_auto_20211210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='post_office_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.PostOfficeInfo'),
        ),
    ]
