# Generated by Django 2.0.3 on 2021-11-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0007_auto_20211124_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubinfo',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='hubinfo',
            name='upazilla_name',
        ),
        migrations.DeleteModel(
            name='HubInfo',
        ),
    ]
