# Generated by Django 2.0.3 on 2021-11-29 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0008_auto_20211129_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(max_length=50)),
                ('hub_owner_name', models.CharField(max_length=50)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact_no1', models.CharField(max_length=50)),
                ('contact_no2', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/merchant_logo')),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_ac_no', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_banking_no', models.CharField(blank=True, max_length=250, null=True)),
                ('trade_license_no', models.CharField(blank=True, max_length=250, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('district_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
                ('upazilla_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry')),
            ],
        ),
        migrations.CreateModel(
            name='RiderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.CharField(max_length=50)),
                ('hub_owner_name', models.CharField(max_length=50)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact_no1', models.CharField(max_length=50)),
                ('contact_no2', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/merchant_logo')),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_ac_no', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_banking_no', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_name', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_phone_no', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_NID', models.CharField(blank=True, max_length=250, null=True)),
                ('referral_relation', models.CharField(blank=True, max_length=250, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('district_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DistrictEntry')),
                ('upazilla_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.UpazillaEntry')),
            ],
        ),
    ]
