# Generated by Django 2.0.3 on 2021-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0008_whybest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChargeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge Location',
                'verbose_name_plural': 'Delivery Charge Location',
            },
        ),
    ]
