# Generated by Django 2.0.3 on 2021-09-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0009_deliverychargelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChargeWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge Weight Category',
                'verbose_name_plural': 'Delivery Charge Weight Category',
            },
        ),
    ]
