# Generated by Django 2.0.3 on 2021-09-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0010_deliverychargeweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('COD_persent', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('delivery_charge_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeLocation')),
                ('delivery_charge_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeWeight')),
            ],
            options={
                'verbose_name': 'Delivery Charge',
                'verbose_name_plural': 'Delivery Charge',
            },
        ),
    ]
