# Generated by Django 2.0.3 on 2021-12-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0010_auto_20211129_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hubinfo',
            old_name='permanent_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='hubinfo',
            name='present_address',
        ),
    ]
