# Generated by Django 2.0.3 on 2021-12-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0011_riderorder_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderorder',
            name='merchant_info',
        ),
        migrations.AddField(
            model_name='riderorder',
            name='order_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.MerchantOrder'),
        ),
        migrations.AlterField(
            model_name='riderorder',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.PickupLocation'),
        ),
        migrations.AlterField(
            model_name='riderorder',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.RiderInfo'),
        ),
    ]
