# Generated by Django 2.0.3 on 2021-12-04 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0011_auto_20211204_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBnakingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=230)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='hubinfo',
            name='mobile_banking_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MobileBnakingCategory'),
        ),
    ]
