# Generated by Django 2.0.3 on 2021-09-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0011_deliverycharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantorder',
            old_name='collection_time_evening',
            new_name='collection_time',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='collection_time_morning',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='post_office_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.PostOfficeInfo'),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='service_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
