# Generated by Django 2.0.3 on 2021-09-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0012_auto_20210917_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryCharge'),
        ),
    ]
