# Generated by Django 2.0.3 on 2021-12-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0012_auto_20211212_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='order_picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.RiderInfo'),
        ),
    ]
