# Generated by Django 2.0.3 on 2021-12-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0013_merchantorder_order_picked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderorder',
            name='hub_receve_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderorder',
            name='hub_rider_assign_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
