# Generated by Django 2.0.3 on 2021-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0014_auto_20210917_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='collection_date',
            field=models.CharField(max_length=50),
        ),
    ]
