# Generated by Django 2.0.3 on 2021-09-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0015_auto_20210917_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='merchant_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantInfo'),
        ),
    ]
