# Generated by Django 2.0.3 on 2021-12-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0015_auto_20211213_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderorder',
            old_name='final_done',
            new_name='hold',
        ),
        migrations.AddField(
            model_name='riderorder',
            name='order_absent',
            field=models.BooleanField(default=False),
        ),
    ]
