# Generated by Django 2.0.3 on 2021-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0016_merchantorder_merchant_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantorder',
            old_name='service_charge',
            new_name='cod_charge',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='lequed_or_Fragile_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='shipment_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='total_service_charge',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
