# Generated by Django 2.0.3 on 2021-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0018_auto_20210928_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collection Charge',
                'verbose_name_plural': 'Collection Charge',
            },
        ),
        migrations.CreateModel(
            name='ReturnCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Return Charge',
                'verbose_name_plural': 'Return Charge',
            },
        ),
    ]
