# Generated by Django 2.0.3 on 2021-09-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0019_collectioncharge_returncharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='customer_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='in_sorting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
