# Generated by Django 2.0.3 on 2021-10-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0020_auto_20210928_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='collection_amount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
