# Generated by Django 2.0.3 on 2021-10-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0021_merchantorder_collection_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantorder',
            name='customer_absent',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='in_sorting',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='order_placed',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='payment_done',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('1', 'order_placed'), ('2', 'customer_absent'), ('3', 'in_sorting'), ('4', 'payment_done')], max_length=1),
        ),
    ]
