# Generated by Django 2.0.3 on 2021-10-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0022_auto_20211001_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.CollectionPointEntry'),
        ),
        migrations.AlterField(
            model_name='deliverycharge',
            name='delivery_charge_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeLocation'),
        ),
        migrations.AlterField(
            model_name='deliverycharge',
            name='delivery_charge_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.DeliveryChargeWeight'),
        ),
    ]
