# Generated by Django 2.0.3 on 2021-12-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0023_auto_20211215_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderinfo',
            name='modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
