# Generated by Django 2.0.3 on 2021-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0023_auto_20211004_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='COD_persent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
