# Generated by Django 2.2 on 2021-12-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0025_auto_20211215_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantorder',
            name='merchant_info',
        ),
        migrations.RemoveField(
            model_name='merchantorder',
            name='order_picked_by',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='delivered_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_hub', to='durbarapp.HubInfo'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='delivered_rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_rider', to='durbarapp.RiderInfo'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='hub_receve_from_hub_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='hub_receve_from_rider_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='hub_rider_assign_for_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='hub_rider_assign_for_pick_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='pickup_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_hub', to='durbarapp.HubInfo'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='pickup_rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_rider', to='durbarapp.RiderInfo'),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='rider_pick_for_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
