# Generated by Django 2.2 on 2021-12-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0026_auto_20211220_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='delivered_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_hub', to='durbarapp.HubInfo'),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='delivered_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_rider', to='durbarapp.RiderInfo'),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='pickup_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_hub', to='durbarapp.HubInfo'),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='pickup_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_rider', to='durbarapp.RiderInfo'),
        ),
    ]
