# Generated by Django 2.2 on 2021-12-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0027_auto_20211220_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderorder',
            name='order_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantOrder'),
        ),
    ]
