# Generated by Django 2.2 on 2021-12-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0028_auto_20211220_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='merchant_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantInfo'),
        ),
    ]
