# Generated by Django 2.2 on 2021-12-22 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0031_remove_merchantorder_merchant_wise_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='weight_by_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.DeliveryCharge_by_Merchant'),
        ),
    ]
