# Generated by Django 2.2 on 2021-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0032_merchantorder_weight_by_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='bar_code',
            field=models.ImageField(blank=True, null=True, upload_to='images/barcode'),
        ),
    ]
