# Generated by Django 2.2 on 2021-12-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0033_merchantorder_bar_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_amount', models.CharField(blank=True, max_length=50)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('hub_rider_assign_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('hub_receve_time', models.DateTimeField(blank=True, null=True)),
                ('canceled_time', models.DateTimeField(blank=True, null=True)),
                ('hold_time', models.DateTimeField(blank=True, null=True)),
                ('return_cause', models.CharField(blank=True, max_length=200)),
                ('order_status', models.CharField(blank=True, choices=[('1', 'Collect'), ('2', 'Delivered'), ('3', 'collection_submit_to_hub'), ('4', 'return'), ('5', 'return_to_hub')], max_length=1)),
                ('order_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantOrder')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.RiderInfo')),
            ],
        ),
    ]
