# Generated by Django 2.2 on 2021-12-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0034_riderdeliveryorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderdeliveryorder',
            old_name='hub_rider_assign_time',
            new_name='hub_delivery_rider_assign_time',
        ),
    ]
