# Generated by Django 2.2 on 2021-12-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0036_auto_20211227_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdeliveryorder',
            name='return_status',
            field=models.CharField(blank=True, choices=[('1', 'Customer_not_connected_phone'), ('2', 'Wrong_product'), ('3', 'Customer_abbsent_in_address'), ('4', 'Customer_not_interested_to_receve')], max_length=1),
        ),
    ]
