# Generated by Django 2.2 on 2021-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0039_collection_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_ammount',
            name='hub_collection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_ammount',
            name='rider_collection_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
