# Generated by Django 2.2 on 2021-12-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0040_auto_20211229_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_ammount',
            name='collect_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.HubInfo'),
        ),
        migrations.AddField(
            model_name='collection_ammount',
            name='collect_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.RiderInfo'),
        ),
    ]
