# Generated by Django 2.2 on 2021-12-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0041_auto_20211229_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_ammount',
            name='is_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection_ammount',
            name='modify',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PaymentStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_amount', models.CharField(blank=True, max_length=50)),
                ('statement_no', models.CharField(blank=True, max_length=50, null=True)),
                ('is_statement', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('hub_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.HubInfo')),
                ('order_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='durbarapp.MerchantOrder')),
            ],
        ),
    ]
