# Generated by Django 2.2 on 2021-12-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0042_auto_20211231_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatement',
            name='is_statement',
        ),
    ]
