# Generated by Django 2.2 on 2021-12-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0043_remove_paymentstatement_is_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatement',
            old_name='collection_amount',
            new_name='total_collection_amount',
        ),
        migrations.RemoveField(
            model_name='paymentstatement',
            name='order_info',
        ),
    ]
