# Generated by Django 2.2 on 2021-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0044_auto_20211231_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatement',
            name='modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
