# Generated by Django 2.2 on 2022-01-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0047_auto_20220102_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatement',
            name='head_office_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentstatement',
            name='head_office_receved',
            field=models.BooleanField(default=False),
        ),
    ]
