# Generated by Django 2.2 on 2022-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0049_merchantorder_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdeliveryorder',
            name='return_pending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderdeliveryorder',
            name='return_to_hub_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merchantorder',
            name='order_track',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('2', 'assign_for_pick'), ('3', 'picked'), ('4', 'hub_collected_for_ware_house'), ('5', 'in_transit'), ('6', 'hub_collected_for_delevery'), ('7', 'assign_for_delevery'), ('8', 'shiping'), ('9', 'delivered'), ('10', 'hold'), ('11', 'return_pending'), ('12', 'return_to_delevery_hub '), ('13', 'return_to_picking_hub'), ('14', 'assign_for_return'), ('15', 'picked_for_return'), ('16', 'return_to_merchent'), ('17', 'canceled'), ('18', 'picking_hold'), ('19', 'order_absent'), ('20', 'rider_cancel'), ('21', 'merchant_absent')], default='1', max_length=3),
        ),
    ]
