# Generated by Django 2.2 on 2022-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0050_auto_20220103_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantorder',
            old_name='return_to_hub_time',
            new_name='assign_for_return_time',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='picked_for_return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_to_delivery_hub_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_to_pickup_hub_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
