# Generated by Django 2.2 on 2022-01-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0051_auto_20220103_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order_quantity', models.CharField(blank=True, max_length=50)),
                ('statement_no', models.CharField(blank=True, max_length=50, null=True)),
                ('head_office_pending', models.BooleanField(default=True)),
                ('head_office_receved', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=0)),
                ('modifed_by', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('hub_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='durbarapp.HubInfo')),
            ],
        ),
    ]
