# Generated by Django 2.2 on 2022-01-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0053_returnstatement_order_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantorder',
            name='order_track',
            field=models.CharField(blank=True, choices=[('1', 'pending'), ('2', 'assign_for_pick'), ('3', 'picked'), ('4', 'hub_collected_for_ware_house'), ('5', 'in_transit'), ('6', 'hub_collected_for_delevery'), ('7', 'assign_for_delevery'), ('8', 'shiping'), ('9', 'delivered'), ('10', 'hold'), ('11', 'return_pending'), ('12', 'return_to_delevery_hub '), ('13', 'return_pending_picking_hub '), ('14', 'return_to_picking_hub'), ('15', 'assign_for_return'), ('16', 'picked_for_return'), ('17', 'return_to_merchent'), ('18', 'canceled'), ('19', 'picking_hold'), ('20', 'order_absent'), ('21', 'rider_cancel'), ('22', 'merchant_absent')], default='1', max_length=3),
        ),
    ]
