# Generated by Django 2.2 on 2022-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0054_auto_20220104_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnstatement',
            name='order_info',
        ),
        migrations.AddField(
            model_name='merchantorder',
            name='return_statement_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
