# Generated by Django 2.2 on 2022-01-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0056_riderdeliveryorder_return_product_delevery'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantorder',
            name='returned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_rider', to='durbarapp.RiderInfo'),
        ),
    ]
