# Generated by Django 2.2 on 2022-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0057_merchantorder_returned_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderdeliveryorder',
            name='modify',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
