# Generated by Django 2.2 on 2022-01-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durbarapp', '0058_auto_20220107_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_ammount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_ammount',
            name='modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
